# Site
title: NextTalk
description: På NextTalk.io finder du det næste foredrag, event, arrangement, webinar, netværksmøde, morgenmøde, gå-hjem-møde, workshop osv. Det er gratis at deltage i alle arrangementer, og det er gratis for arrangører at bruge NextTalk.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nexttalk.io" # the base hostname & protocol for your site, e.g. http://example.com

# Other
typekit_id: #
html_lang: en

# Social
twitter_username: #
github_username:  #
email: hej@nexttalk.io
google_plus: #

# Analytic
google_analytic: UA-91821612-1
facebook_pixelid: 1200965133318663

# Collections
collections:
  events:
    output: true
    permalink: /events/:title:output_ext

# Defaults
defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: event
      cover_image: http://demo.nexttalk.io/assets/img/eventCover.jpg

# Build settings
markdown: kramdown
permalink: pretty

gems:

exclude:
  - Gemfile
  - Gemfile.lock
  - .deploy.sh
  - "*.jade"
